#!/bin/bash
cp /boot/config/rules.d/60-persistent-storage.rules /etc/udev/rules.d/
chmod 644 /etc/udev/rules.d/60-persistent-storage.rules
cp /boot/config/custom_scripts/get_hdd_info.sh /usr/local/bin/
chmod +x /usr/local/bin/get_hdd_info.sh

udevadm control --reload-rules
udevadm trigger

# Start the Management Utility
/usr/local/sbin/emhttp
